### ISSUE TITLE
Decoding Double as Float

### ISSUE THREAD

**Issue by ksemianov** [Flight-School/MessagePack#17]
If I decode a `Double` value as a `Float`, it silently reinterprets the first 32 bits and gives garbage results. What behaviour is intended? Should it throw `DecodingError.typeMismatch`? Should It decode `Double` and then cast to `Float`?

Example:
```swift
import MessagePack

let double = Double(1)
let encoder = MessagePackEncoder()
let data = try encoder.encode(double)
let decoder = MessagePackDecoder()
let float = try decoder.decode(Float.self, from: data)
print(float) // prints 1.875
```

P.S.: Float to Double case gives garbage as well
P.P.S.: there are some typos in specifying some of the `DecodingError.typeMismatch` types in `SingleValueDecodingContainer.swift`

**Comment by mattt** [comment]
Thanks for sharing this feedback, @ksemianov.

I think the preferred behavior would be as follows:

1. By default, attempting to decode `Double` as `Float` (or vice versa) throws `DecodingError.typeMismatch`.
2. As a further enhancement, we can add an option for the decoder to override this behavior. (If we add this, we should provide equivalent options for flexibly decoding integer types as well)

If you have some bandwidth to work on this, I'd certainly appreciate a PR that at least throws `typeMismatch`. Same goes for any typos you found in `SingleValueDecodingContainer.swift`.
