### ISSUE TITLE
Decode unsigned integers as signed integers

### ISSUE THREAD

**Issue by Dev1an** [Flight-School/MessagePack#2]
Say someone encoded the number 128 as `<CC 80>` (which is what [the spec](https://github.com/msgpack/msgpack/blob/master/spec.md#serialization-type-to-format-conversion) recommends) and you try to decode this number using this library into a Swift `Int` you will get an error because the unsigned integers are not covered in this switch case:
https://github.com/Flight-School/MessagePack/blob/d9acb58b6a3757f252009a21cf966ddb40c47f8e/Sources/MessagePack/Decoder/SingleValueDecodingContainer.swift#L107

**Comment by mattt** [comment]
Hi @Dev1an. As I described in #3, the number 128 would only be encoded as `<CC 80>` if it were encoded as an unsigned integer. You can't decode signed integers from an encoded unsigned integer, so an error would be expected. The format byte range you described is covered in the `UInt` overload here: https://github.com/Flight-School/MessagePack/blob/d9acb58b6a3757f252009a21cf966ddb40c47f8e/Sources/MessagePack/Decoder/SingleValueDecodingContainer.swift#L146-L163

**Comment by mattt** [comment]
Please see my last message on #3. I agree that the encoded representation `<CC 80>` should be decodable to a signed integer type, and propose to make such a change in this library.

**Comment by Dev1an** [comment]
Cool man! That would be great.

**Comment by mattt** [comment]
As of 377a505, you can now decode any Swift integer type from any MessagePack integer representation. Here's the relevant test case: https://github.com/Flight-School/MessagePack/blob/master/Tests/MessagePackTests/MessagePackDecodingTests.swift#L29-L33
