### ISSUE TITLE
Decode & encode functions are not public

### ISSUE THREAD

**Issue by Dev1an** [Flight-School/MessagePack#4]
The [`func decode<T>(_ type: T.Type, from data: Data) throws -> T where T : Decodable`](https://github.com/Flight-School/MessagePack/blob/d9acb58b6a3757f252009a21cf966ddb40c47f8e/Sources/MessagePack/Decoder/MessagePackDecoder.swift#L7) is not public and hence not available if you depend on this library from another project using [SPM](https://swift.org/package-manager/)

**Comment by Dev1an** [comment]
The same goes for encoding
[`func encode(_ value: Encodable) throws -> Data`](https://github.com/Flight-School/MessagePack/blob/d9acb58b6a3757f252009a21cf966ddb40c47f8e/Sources/MessagePack/Encoder/MessagePackEncoder.swift#L7)

**Comment by mattt** [comment]
Yikes, that's quite an oversight on my part. This is fixed by fc7bcb01a34f3334d512ec70dadce344a05f3386 and eacc966c311ff49561c8b913850f43d00aff6dd4.
